# Generated by Django 5.2.11 on 2026-03-06 06:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0779_attachmentcontent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attachmentcontent",
            name="attachment_content_search_tsvector",
        ),
        migrations.AlterField(
            model_name="attachmentcontent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="attachmentcontent",
            index=django.contrib.postgres.indexes.GinIndex(
                models.F("search_tsvector"),
                fastupdate=False,
                name="attachment_content_search_tsvector",
            ),
        ),
    ]
